# Generated by Django 5.0.7 on 2024-07-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0003_rename_datos_pelicula_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(upload_to='imgPelicula'),
        ),
    ]
