# Generated by Django 5.0.7 on 2024-07-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(default='no disponible', verbose_name='Descripción')),
                ('fecha_lanzamiento', models.DateField(default='no disponible', verbose_name='Fecha de lanzamiento')),
                ('duracion', models.IntegerField(help_text='Duracion en minutos')),
                ('director', models.TextField(default='no disponible', verbose_name='Director')),
                ('genero', models.CharField(default='no disponible', max_length=100)),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
            },
        ),
    ]
