# Generated by Django 5.0.7 on 2024-07-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(help_text='Duración en minutos', verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(default='no disponible', max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
